version: "3.9"
services:
  api:
    container_name: property_management_service
    image: property_management_api
    restart: always
    build: ./server
    ports:
      - 9000:9000
    environment:
      MONGO: mongodb://mongo:27017/test?
      PORT: 9000
      JWT_SECRET: secret
    depends_on:
      - mongo
    networks:
      - mynetwork

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

    networks:
      - mynetwork
  ui:
    container_name: pm_frontend_service
    image: pm_frontend
    restart: always
    build: ./client
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - api
      - mongo
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mongo:
